# Generated by Django 4.2.9 on 2024-02-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatedatamapping',
            name='mapping_expression',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
