# Generated by Django 4.2.10 on 2024-03-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0003_alter_template_model_add_type_dynamic_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatefile',
            name='file_type',
            field=models.CharField(choices=[('PDF', 'Pdf'), ('XLS', 'Xls')], default='PDF', max_length=25),
        ),
    ]
