# Generated by Django 4.2.10 on 2024-02-26 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_name', models.CharField(blank=True, default='', max_length=255)),
                ('billing_address', models.CharField(blank=True, default='', max_length=255)),
                ('site_name', models.CharField(blank=True, default='', max_length=255)),
                ('site_address', models.CharField(blank=True, default='', max_length=255)),
                ('vat_number', models.CharField(blank=True, default='', max_length=255)),
                ('account_number', models.CharField(blank=True, default='', max_length=255)),
                ('msn', models.CharField(blank=True, default='', max_length=32)),
                ('pc', models.CharField(blank=True, default='', max_length=255)),
                ('mtc', models.CharField(blank=True, default='', max_length=255)),
                ('llf', models.CharField(blank=True, default='', max_length=255)),
                ('mpan', models.CharField(blank=True, db_index=True, default='', max_length=21)),
                ('contract_end_at', models.DateTimeField()),
                ('invoice_number', models.CharField(blank=True, default='', max_length=128)),
                ('invoice_at', models.DateTimeField()),
                ('bill_from_at', models.DateTimeField()),
                ('bill_to_at', models.DateTimeField()),
                ('payment_due_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'billing_details',
            },
        ),
        migrations.CreateModel(
            name='HHConsumptionCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_consumption_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('day_consumption_unit', models.CharField(max_length=12)),
                ('day_rate_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('day_rate_unit', models.CharField(max_length=12)),
                ('day_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('night_consumption_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('night_consumption_unit', models.CharField(max_length=12)),
                ('night_rate_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('night_rate_unit', models.CharField(max_length=12)),
                ('night_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_electricity_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'hh_consumption_charges',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start_at', models.DateTimeField()),
                ('period_end_at', models.DateTimeField()),
                ('invoice_at', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='customers.customer')),
                ('electricity_customer_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='customers.electricitycustomeraccount')),
            ],
            options={
                'db_table': 'invoices',
            },
        ),
        migrations.CreateModel(
            name='ReadingConsumptionCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('opening_reading_type', models.CharField(max_length=12)),
                ('opening_reading_date', models.DateField()),
                ('last_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('last_reading_type', models.CharField(max_length=12)),
                ('last_reading_date', models.DateField()),
                ('consumption', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_electricity_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'reading_consumption_charges',
            },
        ),
        migrations.CreateModel(
            name='MeterInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_center_contract_meter_id', models.IntegerField(blank=True, null=True)),
                ('levy_name', models.CharField(max_length=255, null=True)),
                ('levy_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('levy_unit', models.CharField(max_length=12, null=True)),
                ('levy_rate_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('levy_rate_unit', models.CharField(max_length=12)),
                ('levy_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_levies', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_no_vat', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('applicable_vat', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('charged_vat', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bill_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('previous_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('customer_billing_details', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meter_invoice', to='invoices.billingdetail')),
                ('hh_consumption_charges', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meter_invoices', to='invoices.hhconsumptioncharges')),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meter_invoices', to='invoices.invoice')),
                ('reading_consumption_charges', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meter_invoices', to='invoices.readingconsumptioncharges')),
            ],
            options={
                'db_table': 'meter_invoices',
            },
        ),
        migrations.CreateModel(
            name='IndustryCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity_1_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('quantity_1_unit', models.CharField(max_length=12)),
                ('quantity_2_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('quantity_2_unit', models.CharField(max_length=12)),
                ('unit', models.CharField(max_length=12)),
                ('rate_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rate_unit', models.CharField(max_length=12)),
                ('charges', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meter_invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='industry_charges', to='invoices.meterinvoice')),
            ],
            options={
                'db_table': 'industry_charges',
            },
        ),
    ]
