# Generated by Django 4.2.10 on 2024-02-29 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_add_datafilerequests_model'),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meterinvoice',
            name='invoice',
        ),
        migrations.AddField(
            model_name='meterinvoice',
            name='data_file_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meter_invoices', to='documents.datafilerequest'),
        ),
    ]
