# Generated by Django 4.2.10 on 2024-03-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_alter_meterinvoice_model_replace_invoice_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingdetail',
            old_name='billing_address',
            new_name='billing_address_1',
        ),
        migrations.AddField(
            model_name='billingdetail',
            name='billing_address_2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='billingdetail',
            name='billing_address_3',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='billingdetail',
            name='billing_address_4',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='billingdetail',
            name='billing_address_5',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='billingdetail',
            name='billing_city',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='billingdetail',
            name='billing_postal_code',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
