# Generated by Django 4.2.10 on 2024-03-12 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_alter_billingdetail_model_add_billingaddresses_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industrycharges',
            name='rate_unit',
            field=models.CharField(max_length=16),
        ),
    ]
