# Generated by Django 4.2.10 on 2024-03-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_alter_industrycharges_rate_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingdetail',
            name='llf',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='billingdetail',
            name='mtc',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='billingdetail',
            name='pc',
            field=models.IntegerField(null=True),
        ),
    ]
