# Generated by Django 4.2.10 on 2024-03-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_alter_billingdetail_models_alter_pc_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingdetail',
            name='llf',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='billingdetail',
            name='mtc',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
