# Generated by Django 4.2.10 on 2024-02-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentgenerationrequest',
            name='is_production',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
