# Generated by Django 4.2.10 on 2024-02-29 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0002_documentgenerationrequest_is_production'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFileRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('INVOICE', 'Invoice')], default='INVOICE', max_length=45)),
                ('name', models.CharField(max_length=225)),
                ('customers', models.JSONField(null=True)),
                ('contracts', models.JSONField(null=True)),
                ('account_holders', models.JSONField(null=True)),
                ('electricity_customer_accounts', models.JSONField(null=True)),
                ('sites', models.JSONField(null=True)),
                ('mpans', models.JSONField(null=True)),
                ('period_start_at', models.DateField()),
                ('period_end_at', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_file_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'data_file_requests',
            },
        ),
    ]
