# Generated by Django 4.2.10 on 2024-03-04 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_add_datafilerequests_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentdatafile',
            name='data_file_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_documents', to='documents.datafilerequest'),
        ),
        migrations.AlterField(
            model_name='documentdatafile',
            name='file',
            field=models.FileField(null=True, upload_to='data_files/%Y/%m/'),
        ),
    ]
