# Generated by Django 4.2.10 on 2024-03-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_documentdatafile_models_add_datafilerequest_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafilerequest',
            name='xls_file',
            field=models.FileField(null=True, upload_to='data_file/%Y/%m/'),
        ),
    ]
