# Generated by Django 4.2.10 on 2024-03-11 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0002_alter_templatedatamapping_mapping_expression'),
        ('documents', '0005_alter_datafilerequest_model_add_xlsfile_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafilerequest',
            name='document_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_file_requests', to='templates.template'),
        ),
    ]
