# Generated by Django 4.2.10 on 2024-03-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_datafilerequest_models_add_template_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_customer',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
