# Generated by Django 4.2.10 on 2024-03-19 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0007_document_is_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentgenerationrequest',
            name='is_production',
        ),
        migrations.RemoveField(
            model_name='documentgenerationrequest',
            name='user',
        ),
        migrations.AddField(
            model_name='document',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='is_production',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
