# Generated by Django 4.2.10 on 2024-03-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_remove_documentgenerationrequest_is_production_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafilerequest',
            name='error',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='datafilerequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], default='PENDING', max_length=32),
        ),
        migrations.AlterField(
            model_name='document',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='is_production',
            field=models.BooleanField(default=False),
        ),
    ]
