name: build and deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build docker images
        run: |
          docker-compose build
          docker tag proposals-app:latest desaas.azurecr.io/proposals-app:latest
          docker tag proposals-celery:latest desaas.azurecr.io/proposals-celery:latest
          docker tag proposals-celery-beat:latest desaas.azurecr.io/proposals-celery-beat:latest

      - name: Login in azure container registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push docker images
        run: |
          docker push desaas.azurecr.io/proposals-app:latest
          docker push desaas.azurecr.io/proposals-celery:latest
          docker push desaas.azurecr.io/proposals-celery-beat:latest

      - name: Copy deployment configs
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: ${{ secrets.AZURE_SERVER_IP }}
          user: ${{ secrets.AZURE_SERVER_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          port: ${{ secrets.AZURE_SSH_PORT }}
          first_ssh: |-
            cd /home/azureuser/proposals/
            docker-compose stop
            yes | docker kill $(sudo docker ps -q -f name="proposals*") | true
            docker rm -f $(sudo docker ps -a -q -f name="proposals*") | true
            yes | docker system prune -a
            docker login https://${{ secrets.REGISTRY_SERVER }} -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}
            docker pull desaas.azurecr.io/proposals-app:latest
            docker pull desaas.azurecr.io/proposals-celery:latest
            docker pull desaas.azurecr.io/proposals-celery-beat:latest
          scp: |
            ./deploy/* => /home/azureuser/proposals/
          last_ssh: |
            cd /home/azureuser/proposals/
            docker compose -f docker-compose.yaml up -d
